/**
 * Reactive Framework - Vanilla JS Only
 *
 * This version excludes React hooks for use in vanilla JavaScript/browser environments
 */

// Core reactive primitives
export {
  reactive,
  computed,
  computedAsync,
  effect,
  batch,
  isBatchingUpdates,
  scheduleNotification,
  readonly,
  readonlyObject,
  watch,
  watchMultiple,
  watchProperty,
  setDebug,
  isDebugEnabled,
  trackReactive,
  getDebugInfo,
  logTrackedReactive,
  clearDebugTracking,
  ref,
  toRaw,
  markRaw,
  isRaw,
  shallowReactive,
  isReactive,
  isComputed,
  bindText,
  bindHTML,
  bindAttr,
  bindProp,
  bindClass,
  bindStyle,
  bindStyles,
  bindInput,
  render,
  bindMultiple,
  bind,
  escapeHtmlEntities,
  sanitizeHtmlContent,
  isUrlSafe,
  configureReactiveSecurity,
  bindAction,
  onClick,
  onDblClick,
  onInput,
  onChange,
  onSubmit,
  onKeyDown,
  onKeyUp,
  onFocus,
  onBlur,
  onMouseEnter,
  onMouseLeave,
  onScroll,
  onKey,
  onEnter,
  onEscape,
} from "./core";

// Types
export type {
  Reactive,
  Computed,
  ComputedWithDispose,
  AsyncComputed,
  AsyncComputedOptions,
  EffectFn,
  EffectCleanup,
  EffectOptions,
  Unsubscribe,
  WatchSource,
  WatchCallback,
  WatchOptions,
  BindingSource,
  BindingOptions,
  SecurityConfig,
  MultiBinding,
  ActionOptions,
  ActionHandler,
  KeyFilter,
} from "./core";
