/**
 * Reactive — lightweight, framework-agnostic reactive state management
 */

export {
  // Core reactivity
  reactive,
  computed,
  computedAsync,
  effect,
  batch,
  isBatchingUpdates,
  readonly,
  readonlyObject,
  watch,
  watchMultiple,
  watchProperty,
  // Utilities
  ref,
  toRaw,
  markRaw,
  isRaw,
  shallowReactive,
  isReactive,
  isComputed,
  // Debug
  setDebug,
  isDebugEnabled,
  trackReactive,
  getDebugInfo,
  logTrackedReactive,
  clearDebugTracking,
  // Template parser
  mount,
  unmount,
  parse,
  autoMount,
  registerState,
  unregisterState,
  clearRegistry,
  buildScope,
  getStateNames,
  // Expression utilities
  evaluate,
  execute,
  compileExpression,
  compileStatement,
  parseInterpolations,
  hasInterpolation,
  clearExpressionCache,
  // DOM bindings
  bindText,
  bindHTML,
  bindAttr,
  bindProp,
  bindClass,
  bindStyle,
  bindStyles,
  bindInput,
  bindMultiple,
  bind,
  render,
  // Events
  bindAction,
  onClick,
  onDblClick,
  onInput,
  onChange,
  onSubmit,
  onKeyDown,
  onKeyUp,
  onFocus,
  onBlur,
  onMouseEnter,
  onMouseLeave,
  onScroll,
  onKey,
  onEnter,
  onEscape,
  // Security
  escapeHtmlEntities,
  sanitizeHtmlContent,
  isUrlSafe,
  configureReactiveSecurity,
} from "./core";

export type {
  Reactive,
  Computed,
  ComputedWithDispose,
  AsyncComputed,
  AsyncComputedOptions,
  EffectFn,
  EffectCleanup,
  EffectOptions,
  Unsubscribe,
  WatchSource,
  WatchCallback,
  WatchOptions,
  BindingSource,
  BindingOptions,
  MultiBinding,
  ActionOptions,
  ActionHandler,
  KeyFilter,
  InterpolationPart,
  TemplateScope,
  CompiledExpression,
  CompiledStatement,
} from "./core";
